
exports.getInteger = async (req, res, next) => {
      try {
         
      } catch (error) {
          return res.status(500).json({ message: "Internal server error." })
      }
  }
